name: stores
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  flutter_bloc: ^8.1.5
  geolocator: ^11.0.0
  path: ^1.9.0
  shared_preferences: ^2.2.2
  bloc: ^8.1.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
